name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Setup testing application
        run: cd tests ; ./install.sh ${{ github.sha }}

      - name: Run tests
        run: cd tests/blog ; php artisan test
